### ISSUE TITLE
404 failed to load resources

### ISSUE THREAD

**Issue by boyana86** [seanmavley/ionic2-sidemenu-tabs#1]
Hi Sean,
I tried  to work on your template however I got these errors... any suggestion related with them? 
http://localhost:8100/build/js/es6-shim.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8100/build/js/angular2-polyfills.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8100/build/js/app.bundle.js Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by seanmavley** [comment]
What steps did you follow? I just tried the approach below and it worked.

Do this:
- Clone the repository: `git clone https://github.com/seanmavley/ionic2-sidemenu-tabs`
- `cd ionic2-sidemenu-tabs`
- `npm install`
- `ionic serve -l`

Do not use the other option. I've removed that from the readme.

**Comment by boyana86** [comment]
![image](https://cloud.githubusercontent.com/assets/2298305/16271428/ac1d8070-38a2-11e6-80db-d32a61dc046f.png)

I did exactly what you said... now I am checking code and  it says "import declarations are not supported by current JavaScript version" I guess I have basic problem related with ecma6 ... Which IDe are you using? I am using Webstorm and I activated ecma6 js version. still not able to see some declarations like "import"

**Comment by seanmavley** [comment]
Well, I use Sublime Text 3 and code works.

I have no idea how WebStorm works or how to use the es6 in WebStorm. You
might have to check the web for guide.
