### ISSUE TITLE
When I build android --prod, error coming :TypeError: Cannot read property 'codeGen' of undefined

### ISSUE THREAD

**Issue by YuyangHYY** [seanmavley/ionic2-sidemenu-tabs#10]
TypeError: Cannot read property 'codeGen' of undefined
And google still no answer can solved this problem.

**Comment by seanmavley** [comment]
@YuyangHYY and your ionic environment info is what?

**Comment by YuyangHYY** [comment]
I solved this error already, because the ionic version problem
