### ISSUE TITLE
how do I include this in an existing project

### ISSUE THREAD

**Issue by oseifrimpong** [seanmavley/ionic2-sidemenu-tabs#3]
I am already building an app. It has gotten to the stage where I will need a side-menu. How do I include this? I have tried but I turn to get the result below:
![ss](https://cloud.githubusercontent.com/assets/3536601/19504670/af0c9010-95ee-11e6-904d-a92e7471147c.png)

**Comment by oseifrimpong** [comment]
Any Idea?

**Comment by seanmavley** [comment]
@oseifrimpong There's little to none I can do to assist if I don't know what your code is.

**Comment by oseifrimpong** [comment]
@seanmavley 
Okay, below are the codes.

app.ts

```
import { Component, ViewChild } from '@angular/core';
import { ionicBootstrap, Platform, MenuController, NavController } from 'ionic-angular';
import { StatusBar } from 'ionic-native';


//pages
import { WelcomePage} from './pages/welcome/welcome';
import { HomePage } from './pages/home/home';
// import { LoginModalPage } './pages/login-modal/login-modal';
// import {}
//import { ionicBootstrap } from 'ionic-angular';



@Component({
    templateUrl: 'build/app.html',
   //template: '<ion-nav [root]="rootPage"></ion-nav>',
  providers: [NavController]

})

export class MyApp {
    @ViewChild('nav') nav : NavController;
    private rootPage: any;
    private pages: any[];


  constructor(public platform: Platform, private menu: MenuController) {
    this.menu = menu;
    this.pages =[

            { title: 'Home', component: HomePage},

        //set pages for the menu
        ];
  //set rootPage    
    this.rootPage = WelcomePage;

    platform.ready().then(() => {
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      StatusBar.styleDefault(); 
    });
  }

  openPage(page) {
    this.menu.close()
    this.nav.push(page.component);
  };
}

ionicBootstrap(MyApp);

```

app.html

```
<ion-menu [content]="content">
    <ion-toolbar>
        <ion-title>Regilex</ion-title>
    </ion-toolbar>
    <ion-content>
        <ion-list>
            <button ion-item *ngFor="let p of pages" (click)="openPage(p)">
                {{p.title}}
            </button>
        </ion-list>
    </ion-content>
</ion-menu>
<ion-nav id="nav" #nav [root]="rootPage" #content swipe-back-enabled="true"></ion-nav>
```

**Comment by seanmavley** [comment]
You know what, your project is based in TypeScript plus from the look of the imports, you're using the most recent Ionic version.

I'll finish a side menu tabs project using the latest Ionic before the end of today. Thanks

**Comment by seanmavley** [comment]
@oseifrimpong By the way, have you seen this? https://github.com/seanmavley/ionic2-sidemenu-tabs/tree/typescript

**Comment by oseifrimpong** [comment]
@seanmavley Yes, I have seen it. That is what helped me to write my come. Then after running, i get that error.

**Comment by seanmavley** [comment]
@oseifrimpong Okay, then maybe you can go about your app the other way, starting from this template then incorporating your changes. 

I just pushed a new branch using the latest update from Ionic, probably the one you're using: https://github.com/seanmavley/ionic2-sidemenu-tabs/tree/2.0-rc.1

**Comment by oseifrimpong** [comment]
Okay! Let me try that. Thanks!

**Comment by oseifrimpong** [comment]
@seanmavley Hi there, I have been able to do it. I forgot to include the menuToggle button on the page I was expecting the menu. I had to use `templateUrl` instead of `template` to load the app.html. 

Appreciate
