### ISSUE TITLE
Why does this only work with ionic labs?

### ISSUE THREAD

**Issue by ghost** [seanmavley/ionic2-sidemenu-tabs#4]
I have done a simple ionic serve and the tabs do not show up, however they do show up when i serve it through the labs. Would you by any chance know why this is happening?

**Comment by seanmavley** [comment]
@TimothyCuthbert Unfortunately, I don't. What version of Ionic are you using? Many parts have changed in recent Ionic version so if you're using any version other than what was used for this project, then I'm sorry I don't know what have changed.

**Comment by seanmavley** [comment]
@TimothyCuthbert See the new change using Ionic 2 final here: https://github.com/seanmavley/ionic2-sidemenu-tabs/tree/2.0-rc.1

**Comment by vnetonline** [comment]
It seems my version is different and cant get it to work with ionic serve

Your system information:

Cordova CLI: 6.4.0 
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
ios-deploy version: Not installed
ios-sim version: Not installed
OS: macOS Sierra
Node Version: v7.2.1
Xcode version: Not installed


can you please help with what should i change in packages.json

**Comment by seanmavley** [comment]
@vnetonline I'll try and let you know. Many things have changed with the Ionic CLI, I guess, so will take a look

**Comment by seanmavley** [comment]
Updated to Ionic 2 Final version 2.0.0.
