### ISSUE TITLE
@Page

### ISSUE THREAD

**Issue by frpz** [seanmavley/ionic2-sidemenu-tabs#6]
Hello,

I'm trying to settup a new project, and i'm having a hard time figuring out which is the recommended file structure and syntax.
For instance, I thought that the @page decorator was deprecated, isn't it?
Also in the sidemenu example, there is a app.modules.ts file, but not in this one.
And are the files supposed to be in src/ or app/ or src/app/ ?

Thanks for your help.
Francis

**Comment by seanmavley** [comment]
@frpz Hi Francis.

There're three branches on this repository. What you're looking for (the most recent update to Ionic) is in this branch: https://github.com/seanmavley/ionic2-sidemenu-tabs/blob/2.0-rc.1/src/app/app.module.ts

**Comment by frpz** [comment]
Ok it's strange, I thought I looked at this branch, but obviously I didn't.
Thanks for your answer.

**Comment by seanmavley** [comment]
Great. Glad you found it.
