### ISSUE TITLE
Tabs appearing only at tabs option

### ISSUE THREAD

**Issue by shivam5x** [seanmavley/ionic2-sidemenu-tabs#7]
Hi,
 I am new for ionic 2, and i have setup your code & working fine , but it is not showing tabs at every page ,so how will i be able to do?

Thanks

**Comment by seanmavley** [comment]
> but it is not showing tabs at every page

I don't understand what you wish to achieve. I'll recommend you use the comment section of the associated article: https://blog.khophi.co/ionic-2-side-menu-tabs/ for asking questions like these, whiles issues here are strictly for issues relating to the project either not working or a bug somewhere.

Thanks.
