### ISSUE TITLE
Side Menu in Ionic 2 to be opened permanently when resolution more than 768px.

### ISSUE THREAD

**Issue by agopikrishna** [seanmavley/ionic2-sidemenu-tabs#8]
Hi,
In Ionic 2. I have disabled the closing of side menu while selecting the menu item with commenting this.menu.close() in openPage(). but when I'm clicking or tapping on outside the side menu the side menu is closing. I need the side menu to be opened when resolution is more than 768px.
![I need the side menu to be opened when resolution is more than 768px](https://cloud.githubusercontent.com/assets/17193053/20637959/d196334c-b3bd-11e6-968a-6da7ad3df63a.png)
But when tapping or clicking outside the side menu closes the side menu.
![But when tapping or clicking outside the side menu closes the side menu.](https://cloud.githubusercontent.com/assets/17193053/20637971/fb620a48-b3bd-11e6-9828-e1e829c6fbce.png)

How can I prevent the closing of side menu when tapping or clicking outside the side menu in Ionic 2?

**Comment by wspresto** [comment]
I was able to get the menu to stick open by calling enable(false,...) with the menu controller. My issue was getting the user to interact with the content once it was locked open.

**Comment by seanmavley** [comment]
@wspresto Hi, Thanks for the input.
Did you get the users to interact well once the menu was open?
