### ISSUE TITLE
use one style for all platforms

### ISSUE THREAD

**Issue by Alkasih** [seanmavley/ionic2-sidemenu-tabs#9]
Hi, I clone the 2.0-rc.1. And it is good. Can you please help me how to use only one style module for all platforms, means that they are not having different tab position in Android, IOS, as well as in browser.

**Comment by seanmavley** [comment]
The style changes depending on the platform the Ionic is built for. So if you want to change the tab position in the respective platform:

See here for more details: http://stackoverflow.com/a/27915387/1757321
